/**
 * Created by Chris Ho on 8/17/2016.
 */
export const FIRST_NAME = 'Please enter your first name';
export const LAST_NAME = 'Please enter your last name';
export const EMAIL = 'Please enter your email address';
export const EMAIL_INVALID = 'The email address entered is invalid';
export const PHONE_NUMBER = 'Please enter your phone number';
export const PHONE_NUMBER_INVALID = 'The phone number entered is invalid';
export const COMPANY_NAME = 'Please enter your company name';
export const COMPANY_SIZE = 'Please select your company size';
export const COUNTRY = 'Please select your country';
export const PASSWORD = 'Please enter password';
export const EXISTED_EMAIL = 'Sorry, it seems like this email address is already registered';
export const PASSWORD_INVALID = 'Password needs to be at least 8 characters long, and needs to include at least 1 digit, 1 upper case character and 1 special character';
export const PASSWORD_NOT_MATCH = 'Passwords entered is not match';
export const SENT_EMAIL_SUCCESSFULLY = 'Password reset link was sent successfully.';
export const CHECK_INBOX_MESSAGE = 'Please check your inbox to reset password.';
export const RESET_PASS_SUCCESS = 'Your password has been reset successfully';
export const UN_CHECK_TERM = 'You must agree with FLOW\'s terms and conditions before purchasing.';
export const CARD_NUMBER = 'Please enter your card number.';
export const CARD_NUMBER_INVALID = 'Card number entered is invalid.';
export const CARD_EXPIRES = 'Please enter expires month and year.';
export const CARD_EXPIRES_INVALID = 'Invalid month and year.';
export const CARD_CVC = 'Please enter cvc.';
export const CARD_INVALID_CVC = 'invalid cvc.';
export const PURCHASE_NOT_SUCCESSFUL = 'Unfortunately, the payment was not successful. Please try again.';
export const BILLING_ADDRESS = 'Please enter your billing address';
export const VAT = 'Please your company’s VAT ID';
// export const VAT_INVALID = 'VAT ID should have at least 10 characters and the first two characters cannot be digits.';
export const VAT_INVALID = 'The VAT ID provided is not valid. Please enter a valid VAT ID to proceed without VAT charges.';
export const BILLING_CITY = 'Please enter the city of your billing address';
export const STATE = 'Please enter the state or province of your billing address';
export const POST_CODE = 'Please enter the postcode of your billing address';
export const BILLING_COUNTRY = 'Please enter the country of your billing address';
export const NOT_FIND_ACCOUNT = 'We cannot find any account associated with the email entered.';
export const ERROR_500 = 'Cannot connect to server.';
export const LOGIN_FAIL = 'Your account entered is incorrect.';
export const PLAN_NOT_SELECTED = 'Please select a plan.';
export const SEAT_NOT_SELECTED = 'Please enter a number of seats.';
export const COUPON_INVALID = 'Coupon entered is invalid.';
export const COUPON_EMPTY = 'Please enter coupon.';

export const SURVEY_SENDER = 'Please enter your name';
export const SURVEY_SUBJECT = 'Please enter your subject';
export const SURVEY_NO_EMAIL = 'Respondents should be at least one email';
export const RESPONDENTS_FIRST_NAME = 'Please enter the first name of the respondent';
export const RESPONDENTS_LAST_NAME = 'Please enter the last name of the respondent';
export const RESPONDENTS_EMAIL = 'Please enter the email address of the respondent';
export const SELECT_RESPONDENTS = 'Please select where you would like to add the respondent to';
export const COPY_PASTE_WRONG_EMAIL = 'Invalid email address/addresses have been detected. Please double check and try again.';
export const COPY_PASTE_WRONG_FORMAT = 'Each row should not be more than 2 commas.';
export const COPY_PASTE_MISS_FIRST_NAME = 'Some rows may have missing first names and or last names. Please double check and try again.';
export const PASTE_RESPONDENTS = 'Please paste respondent contact information in the textbox';
export const EMAIL_EXISTING_IN_THIS_PACKAGE = 'The email has been existed in this package';
export const EMAIL_EXISTING_IN_OTHER_PACKAGE = 'The email has been existed in other package. Please make it inactive before adding it to this package';
export const SENT_SURVEY_SUCCESSFULLY = 'Survey was sent successfully.';
export const ADD_RESPONDENT_OVER_VOLUME = 'The number of respondents has exceeded number of package purchased';

